version: 1.0.{build}
skip_branch_with_pr: true
max_jobs: 8

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform: Any CPU

build:
  verbosity: minimal

before_build:
  - nuget restore

test_script:
  - cmd: vstest.console ItcLabAnalyzer\ItcLabAnalyzer.Test\bin\%CONFIGURATION%\netcoreapp2.0\ItcLabAnalyzer.Test.dll
